# Node.js Function App to Linux on Azure
# Build a Node.js function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 paths:
   include:
     - data-access
 branches:
   include:
     - main

pr: none
  
variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '5c39f733-98b0-4191-82f4-9c124a4df205'

  # Function app name
  functionAppName: 'data-access'
 
  # Environment name
  environmentName: 'data-access'
 
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  system.debug: true
  
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'



    - task: FuncToolsInstaller@0
      inputs:
        version: '3.0.2931'

    - script: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      displayName: 'Build extensions'

    - task: Bash@3
      displayName: 'Prepare binaries'
      inputs:
        targetType: 'inline'
        script: |
          npm cache clean
          npm install
          npm run build
        workingDirectory: 'data-access'
      
      
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:            
          - task: AzureFunctionApp@1
            displayName: 'Azure Functions App Deploy: data-access'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: 'runFromPackage'
          - task: AzureFunctionApp@1
            displayName: 'Azure Functions App Deploy: data-access-west'
            inputs:
              azureSubscription: 'Visual Studio Enterprise(1)(1e23aa72-fb0d-424b-a48c-0de4916aee72)'
              appType: 'functionAppLinux'
              appName: 'data-access-west'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: 'runFromPackage'