trigger:
 paths:
   include:
     - ui
 branches:
   include:
     - main

pr: none
  
variables:
    system.debug: true

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build_stage
  displayName: Build Stage
  jobs:
  - job: build_job
    displayName: Build Job
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'simnova'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sharethrift-ui'
        cliProjectName: 'sharethrift-ui'
        cliSources: './ui/src'
    - template: ./build-pipeline/npm-build.yml
      parameters:
        buildPath: 'ui'
        archivePath: 'ui/build'
        archiveName: 'prod'
        buildEnvSettings:
          INLINE_RUNTIME_CHUNK: 'false'
          REACT_APP_AAD_APP_CLIENTID: $(REACT_APP_AAD_APP_CLIENTID)
          REACT_APP_AAD_DIRECTORY_TENANTID: $(REACT_APP_AAD_DIRECTORY_TENANTID)
          REACT_APP_AAD_REDIRECT_URI: $(REACT_APP_AAD_REDIRECT_URI)
          REACT_APP_AAD_SCOPES: $(REACT_APP_AAD_SCOPES)
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'www'
        publishLocation: 'Container'

- stage: deploy_qa_stage
  dependsOn: build_stage
  displayName: Deploy QA Stage
  jobs:
  - deployment: deploy_qa_job
    displayName: Deploy QA Job
    environment: verify-cs-qa
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
          - template: ./build-pipeline/deploy.yml
            parameters:
              subscription: $(azureSubscription)
              destinationBlobContainer: 'sharethriftqa'
              archiveName: 'prod'
              cdnProfile: 'sharethrift'
              cdnResourceGroup: 'rg-sharethrift'
              cdnName: 'sharethriftqa'

- stage: deploy_prod_stage
  dependsOn: deploy_qa_stage
  displayName: Deploy Prod Stage
  jobs:
  - deployment: deploy_prod_job
    displayName: Deploy Prod Job
    environment: verify-cs-prod
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
          - template: ./build-pipeline/deploy.yml
            parameters:
              subscription: $(azureSubscription)
              destinationBlobContainer: 'sharethrift'
              archiveName: 'prod'
              cdnProfile: 'sharethrift'
              cdnResourceGroup: 'rg-sharethrift'
              cdnName: 'sharethrift'