# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 paths:
   include:
     - ui
 branches:
   include:
     - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: ui




- task: AzureCLI@2
  displayName: Az File Copy to Storage
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch \
                --destination \$web \
                --account-name "$(storageAccountName)" \
                --source "ui/dist"


- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureSubscription)
    ScriptType: 'InlineScript'
    Inline: 'cdn endpoint purge --profile-name sharethrift -g PWP-ResourceGroup -n rg-sharethrift --content-paths "/*"'